### ISSUE TITLE
Fan module: Weak point - Crank_Handle-2 STL

### ISSUE THREAD

**Issue by DillonSimeone** [gearfinity/gearfinity#2]
Why is this little area thinner than the rest of the handle? It really weakens the Crank_Handle-2 STL, to an extent where it snapped within one minutes of using. 

![image](https://github.com/gearfinity/gearfinity/assets/21962421/415b7fc0-d02e-4b0c-b909-00e1bacc30a0)

I cut it in the Bambu slicer, and adjusted it so it's like this:

![image](https://github.com/gearfinity/gearfinity/assets/21962421/424b15fb-cb7c-4cd2-a0d1-b6f0d0552575)

This should be much more durable. Durability aside, this part would be improved if the handle was free-rotating.

**Comment by gearfinity** [comment]
Ah, this is a great point that I've absent-mindedly left out of instructions. The handle is actually meant to be free rotating. After printing if you twist it directly around it's axis it should break free at the thin part. See the cross-section image below for better insight into how it is separate from the inner axle.

![crank_handle_cross_section](https://github.com/gearfinity/gearfinity/assets/139299901/af20dfe0-6739-4960-8ef0-d4612db70fa8)

**Comment by DillonSimeone** [comment]
Ah, wow! Nice.

Hmm... Maybe a ball joint would be more durable? 

![image](https://github.com/gearfinity/gearfinity/assets/21962421/bc6ca748-7022-40b5-a40a-cdd7f2bf005b)

![image](https://github.com/gearfinity/gearfinity/assets/21962421/17066359-a72d-4319-bcb1-a83245d85928)

I could increase my infill to 100% and see how this shakes out. I accidentally printed this on the default setting of 15% infill, it turns out. Seven hours until my printer finish printing the modified parts, too far in to pull out, kek.

Turning the broken crank on the finished piece have me thinking that a hole big enough for a finger or two to fit through would do just fine for full-strength rotating. Man, I'm exicited to really get elbow-deep into those gears! Put a Ugrinsky wind turbine on top of one of the modules... Spin a motor, recharge a railgun's capacitor bank after about a decade of gentle breeze! 

![image](https://github.com/gearfinity/gearfinity/assets/21962421/67da7ba2-3ebd-404a-bcc4-6dd68103fa00)

**Comment by gearfinity** [comment]
Looking good!

Yeah a higher infill could definitely help. I've got some beefier, multi-part crank handles in the works that won't break as easy (just require a little bit more assembly).

Thanks for the pics!
