### ISSUE TITLE
Fan module: Weak point - Handle-1, Gearbox_cover and handle_plate

### ISSUE THREAD

**Issue by DillonSimeone** [gearfinity/gearfinity#3]
I get that you was trying to make all of those parts printable without support, but sadly, as is, those parts kept coming apart really easily. I've sliced and modified the parts slightly in the Bambu slicer as you can see below:

![image](https://github.com/gearfinity/gearfinity/assets/21962421/81a90f01-a38f-4af3-b578-a88f8f98b2a4)

This is what it looks like in my slicer with supports. Just 3g of supports. Meh.

![image](https://github.com/gearfinity/gearfinity/assets/21962421/9f1c1890-e3c5-4637-bbc4-43c6c7e09058)

Tried in other directions just in case. 

![image](https://github.com/gearfinity/gearfinity/assets/21962421/7b6dcb8b-7673-4807-92dd-3e8b94c24359)

**Comment by DillonSimeone** [comment]
🤔 Have me wondering if the short pins and long pins isn't the ideal approach here... Maybe making lego-like assets that can be assembled in any slicer softwares, then printed out as one solid indestructible piece?

**Comment by gearfinity** [comment]
Could you specify which parts are coming loose? The common problem I've run into is the handle plate coming off of the gearbox. I had designed a backet to prevent this but I just now got around to uploading it:

https://github.com/gearfinity/gearfinity/blob/main/_all_parts/handle_plate_bracket_half-1.STL

You can see how it's assembled here:

https://www.youtube.com/shorts/OGo2ZauXTeQ

**Comment by DillonSimeone** [comment]
Oh wow, now this is ingenious! Keeping in line of the spirit of extreme modularity when not compromising too much on durability! 

Yes, the plate was coming off constantly. I'm still printing... Halfway finished, the 3D printer got tangled when I was sleeping. Darn! My fault for putting a new reel in in total darkness with one arm.

**Comment by gearfinity** [comment]
Haha, yeah in my experience so far the flexibility that modularity provides opens up opportunities to design parts in a way that actually capitalizes on the strengths of 3D printing.

For instance, the bracket as a single part would need to be printed standing up if no supports were used, like this:

![bracket_single_part](https://github.com/gearfinity/gearfinity/assets/139299901/3a47e584-9446-45f1-8282-53d53d1aacdb)

This makes the bracket arms much more fragile as the grain would be perpendicular to the "length" of the part. But as two parts:

![bracket_two_part](https://github.com/gearfinity/gearfinity/assets/139299901/13c91d19-56ec-4e38-bc90-7c7433678e81)

The layer grain and the arms are much stronger.

Also, having an "intended" print arrangement allows for built-in supports, which I much prefer over the slicer generated supports.

**Comment by DillonSimeone** [comment]
![image](https://github.com/gearfinity/gearfinity/assets/21962421/8c208ab4-b79e-4c0e-8584-33c03bf70e86)
![image](https://github.com/gearfinity/gearfinity/assets/21962421/c416306a-a316-4da4-88e2-660810f74fa1)
![image](https://github.com/gearfinity/gearfinity/assets/21962421/02eafdf8-5b7e-4739-84bc-d6dc6d524291)

Imagine the look on my face when I connected the new crank, only for it to explode like this when turned at full power, kek

![image](https://github.com/gearfinity/gearfinity/assets/21962421/e1e8bb50-d129-4554-afc3-09beb033b74c)


This is really lending weight to your approach of going really modular... If a piece breaks, print out a new replacement and slam that in! Seems that there's a bad line going across everything I printed due to swapping 3D print filaments mid-print. Oof!

A quick sweep over an open flame ought do nicely for the new heavy-duty non-modular frame I made...

**Comment by DillonSimeone** [comment]
ANYWAY. Glad that this got more modular parts shaking out of the modular bag! Durability issue resolved!

**Comment by gearfinity** [comment]
@DillonSimeone great pics! Thanks for sharing 😄
